name: 'Docker image serialization'
description: 'Serialize Docker images between jobs'
inputs:
  serialize:
    description: 'Docker images to serialize'
    required: false
    default: ''
  restore:
    description: 'Restore all Docker images'
    required: false
    default: 'false'
runs:
  using: 'node12'
  main: 'dist/index.js'
